[tokenizer]
merges_path = "path/to/merges.txt"
vocab_path = "path/to/vocab.json"
special_tokens = ["<|pad|>", "<|eos|>"]

[model]
vocab_size = 50257
context_length = 256
d_model = 512
num_layers = 4
num_heads = 16
d_ff = 1344
rope_theta = 10000.0
device = "cuda"       # or "spu"
dtype = "float32"     # "float32" | "float16" | "bfloat16"

[checkpoint]
ckpt_path = "path/to/checkpoint.pt"

[inference]
text_list = [
  "Once upon a time,",
  "In a distant galaxy,",
]
temperature = 1.0
p = 0.9
eos_token_id = 1

[benchmark]
warmup = 10
repeats = 20
steps = 64
synchronize = true

[logging]
backend = "console"
run_name = ""
architecture = "TransformerLM"
dataset = "synthetic"
